[package]
name = "bevy_schedule_hook"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
bevy_ecs = "0.11"
bevy_app = "0.11"
bevy_utils = "0.11"
bevy_schedule_dispatch = "0.1.1"
retour = { version = "0.3", features = ["static-detour", "thiscall-abi"] }
